# Generated by Django 4.2.3 on 2023-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
            ],
        ),
    ]
